//
//  Countries.swift
//  CountryListExample
//
//  Created by Juan Pablo on 9/8/17.
//  Copyright © 2017 Juan Pablo Fernandez. All rights reserved.
//

import UIKit

import UIKit

class Countries {
    
    var countries: [CountryPod] = {
        var countries: [CountryPod] = []
        
        countries.append(CountryPod(countryCode: "AF", phoneExtension: "93"))
        countries.append(CountryPod(countryCode: "AL", phoneExtension: "355"))
        countries.append(CountryPod(countryCode: "DZ", phoneExtension: "213"))
        countries.append(CountryPod(countryCode: "AS", phoneExtension: "1"))
        countries.append(CountryPod(countryCode: "AD", phoneExtension: "376"))
        countries.append(CountryPod(countryCode: "AO", phoneExtension: "244"))
        countries.append(CountryPod(countryCode: "AI", phoneExtension: "1"))
        countries.append(CountryPod(countryCode: "AQ", phoneExtension: "672"))
        countries.append(CountryPod(countryCode: "AG", phoneExtension: "1"))
        countries.append(CountryPod(countryCode: "AR", phoneExtension: "54"))
        countries.append(CountryPod(countryCode: "AM", phoneExtension: "374"))
        countries.append(CountryPod(countryCode: "AW", phoneExtension: "297"))
        countries.append(CountryPod(countryCode: "AU", phoneExtension: "61"))
        countries.append(CountryPod(countryCode: "AT", phoneExtension: "43"))
        countries.append(CountryPod(countryCode: "AZ", phoneExtension: "994"))
        
        
        countries.append(CountryPod(countryCode: "BS", phoneExtension: "1"))
        countries.append(CountryPod(countryCode: "BH", phoneExtension: "973"))
        countries.append(CountryPod(countryCode: "BD", phoneExtension: "880"))
        countries.append(CountryPod(countryCode: "BB", phoneExtension: "1"))
        countries.append(CountryPod(countryCode: "BY", phoneExtension: "375"))
        countries.append(CountryPod(countryCode: "BE", phoneExtension: "32"))
        countries.append(CountryPod(countryCode: "BZ", phoneExtension: "501"))
        countries.append(CountryPod(countryCode: "BJ", phoneExtension: "229"))
        countries.append(CountryPod(countryCode: "BM", phoneExtension: "1"))
        countries.append(CountryPod(countryCode: "BT", phoneExtension: "975"))
        countries.append(CountryPod(countryCode: "BO", phoneExtension: "591"))
        countries.append(CountryPod(countryCode: "BA", phoneExtension: "387"))
        countries.append(CountryPod(countryCode: "BW", phoneExtension: "267"))
        countries.append(CountryPod(countryCode: "BR", phoneExtension: "55"))
        countries.append(CountryPod(countryCode: "IO", phoneExtension: "246"))
        countries.append(CountryPod(countryCode: "VG", phoneExtension: "1"))
        countries.append(CountryPod(countryCode: "BN", phoneExtension: "673"))
        countries.append(CountryPod(countryCode: "BG", phoneExtension: "359"))
        countries.append(CountryPod(countryCode: "BF", phoneExtension: "226"))
        countries.append(CountryPod(countryCode: "BI", phoneExtension: "257"))
        countries.append(CountryPod(countryCode: "KH", phoneExtension: "855"))
        countries.append(CountryPod(countryCode: "CM", phoneExtension: "237"))
        countries.append(CountryPod(countryCode: "CA", phoneExtension: "1"))
        countries.append(CountryPod(countryCode: "CV", phoneExtension: "238"))
        
        countries.append(CountryPod(countryCode: "KY", phoneExtension: "1"))
        countries.append(CountryPod(countryCode: "CF", phoneExtension: "236"))
        countries.append(CountryPod(countryCode: "TD", phoneExtension: "235"))
        countries.append(CountryPod(countryCode: "CL", phoneExtension: "56"))
        countries.append(CountryPod(countryCode: "CN", phoneExtension: "86"))
        countries.append(CountryPod(countryCode: "CX", phoneExtension: "61"))
        countries.append(CountryPod(countryCode: "CC", phoneExtension: "61"))
        countries.append(CountryPod(countryCode: "CO", phoneExtension: "57"))
        countries.append(CountryPod(countryCode: "KM", phoneExtension: "269"))
        countries.append(CountryPod(countryCode: "CK", phoneExtension: "682"))
        countries.append(CountryPod(countryCode: "CR", phoneExtension: "506"))
        countries.append(CountryPod(countryCode: "HR", phoneExtension: "385"))
        countries.append(CountryPod(countryCode: "CU", phoneExtension: "53"))
        countries.append(CountryPod(countryCode: "CW", phoneExtension: "599"))
        countries.append(CountryPod(countryCode: "CY", phoneExtension: "357"))
        countries.append(CountryPod(countryCode: "CZ", phoneExtension: "420"))
        countries.append(CountryPod(countryCode: "CD", phoneExtension: "243"))
        
        countries.append(CountryPod(countryCode: "DK", phoneExtension: "45"))
        countries.append(CountryPod(countryCode: "DJ", phoneExtension: "253"))
        countries.append(CountryPod(countryCode: "DM", phoneExtension: "1"))
        countries.append(CountryPod(countryCode: "DO", phoneExtension: "1"))
        
        countries.append(CountryPod(countryCode: "TL", phoneExtension: "670"))
        countries.append(CountryPod(countryCode: "EC", phoneExtension: "593"))
        countries.append(CountryPod(countryCode: "EG", phoneExtension: "20"))
        countries.append(CountryPod(countryCode: "SV", phoneExtension: "503"))
        countries.append(CountryPod(countryCode: "GQ", phoneExtension: "240"))
        countries.append(CountryPod(countryCode: "ER", phoneExtension: "291"))
        countries.append(CountryPod(countryCode: "EE", phoneExtension: "372"))
        countries.append(CountryPod(countryCode: "ET", phoneExtension: "251"))
        
        countries.append(CountryPod(countryCode: "FK", phoneExtension: "500"))
        countries.append(CountryPod(countryCode: "FO", phoneExtension: "298"))
        countries.append(CountryPod(countryCode: "FJ", phoneExtension: "679"))
        countries.append(CountryPod(countryCode: "FI", phoneExtension: "358"))
        countries.append(CountryPod(countryCode: "FR", phoneExtension: "33"))
        countries.append(CountryPod(countryCode: "PF", phoneExtension: "689"))
        
        countries.append(CountryPod(countryCode: "GA", phoneExtension: "241"))
        countries.append(CountryPod(countryCode: "GM", phoneExtension: "220"))
        countries.append(CountryPod(countryCode: "GE", phoneExtension: "995"))
        countries.append(CountryPod(countryCode: "DE", phoneExtension: "49"))
        countries.append(CountryPod(countryCode: "GH", phoneExtension: "233"))
        countries.append(CountryPod(countryCode: "GI", phoneExtension: "350"))
        countries.append(CountryPod(countryCode: "GR", phoneExtension: "30"))
        countries.append(CountryPod(countryCode: "GL", phoneExtension: "299"))
        countries.append(CountryPod(countryCode: "GD", phoneExtension: "1"))
        countries.append(CountryPod(countryCode: "GU", phoneExtension: "1"))
        countries.append(CountryPod(countryCode: "GT", phoneExtension: "502"))
        countries.append(CountryPod(countryCode: "GG", phoneExtension: "44"))
        countries.append(CountryPod(countryCode: "GN", phoneExtension: "224"))
        countries.append(CountryPod(countryCode: "GW", phoneExtension: "245"))
        countries.append(CountryPod(countryCode: "GY", phoneExtension: "592"))
        
        countries.append(CountryPod(countryCode: "HT", phoneExtension: "509"))
        countries.append(CountryPod(countryCode: "HN", phoneExtension: "504"))
        countries.append(CountryPod(countryCode: "HK", phoneExtension: "852"))
        countries.append(CountryPod(countryCode: "HU", phoneExtension: "36"))
        
        countries.append(CountryPod(countryCode: "IS", phoneExtension: "354"))
        countries.append(CountryPod(countryCode: "IN", phoneExtension: "91"))
        countries.append(CountryPod(countryCode: "ID", phoneExtension: "62"))
        countries.append(CountryPod(countryCode: "IR", phoneExtension: "98"))
        countries.append(CountryPod(countryCode: "IQ", phoneExtension: "964"))
        countries.append(CountryPod(countryCode: "IE", phoneExtension: "353"))
        countries.append(CountryPod(countryCode: "IM", phoneExtension: "44"))
        countries.append(CountryPod(countryCode: "IL", phoneExtension: "972"))
        countries.append(CountryPod(countryCode: "IT", phoneExtension: "39"))
        countries.append(CountryPod(countryCode: "CI", phoneExtension: "225"))
        
        countries.append(CountryPod(countryCode: "JM", phoneExtension: "1"))
        countries.append(CountryPod(countryCode: "JP", phoneExtension: "81"))
        countries.append(CountryPod(countryCode: "JE", phoneExtension: "44"))
        countries.append(CountryPod(countryCode: "JO", phoneExtension: "962"))
        
        countries.append(CountryPod(countryCode: "KZ", phoneExtension: "7"))
        countries.append(CountryPod(countryCode: "KE", phoneExtension: "254"))
        countries.append(CountryPod(countryCode: "KI", phoneExtension: "686"))
        countries.append(CountryPod(countryCode: "XK", phoneExtension: "383"))
        countries.append(CountryPod(countryCode: "KW", phoneExtension: "965"))
        countries.append(CountryPod(countryCode: "KG", phoneExtension: "996"))
        
        countries.append(CountryPod(countryCode: "LA", phoneExtension: "856"))
        countries.append(CountryPod(countryCode: "LV", phoneExtension: "371"))
        countries.append(CountryPod(countryCode: "LB", phoneExtension: "961"))
        countries.append(CountryPod(countryCode: "LS", phoneExtension: "266"))
        countries.append(CountryPod(countryCode: "LR", phoneExtension: "231"))
        countries.append(CountryPod(countryCode: "LY", phoneExtension: "218"))
        countries.append(CountryPod(countryCode: "LI", phoneExtension: "423"))
        countries.append(CountryPod(countryCode: "LT", phoneExtension: "370"))
        countries.append(CountryPod(countryCode: "LU", phoneExtension: "352"))
        
        countries.append(CountryPod(countryCode: "MO", phoneExtension: "853"))
        countries.append(CountryPod(countryCode: "MK", phoneExtension: "389"))
        countries.append(CountryPod(countryCode: "MG", phoneExtension: "261"))
        countries.append(CountryPod(countryCode: "MW", phoneExtension: "265"))
        countries.append(CountryPod(countryCode: "MY", phoneExtension: "60"))
        countries.append(CountryPod(countryCode: "MV", phoneExtension: "960"))
        countries.append(CountryPod(countryCode: "ML", phoneExtension: "223"))
        countries.append(CountryPod(countryCode: "MT", phoneExtension: "356"))
        countries.append(CountryPod(countryCode: "MH", phoneExtension: "692"))
        countries.append(CountryPod(countryCode: "MR", phoneExtension: "222"))
        countries.append(CountryPod(countryCode: "MU", phoneExtension: "230"))
        countries.append(CountryPod(countryCode: "YT", phoneExtension: "262"))
        countries.append(CountryPod(countryCode: "MX", phoneExtension: "52"))
        countries.append(CountryPod(countryCode: "FM", phoneExtension: "691"))
        countries.append(CountryPod(countryCode: "MD", phoneExtension: "373"))
        countries.append(CountryPod(countryCode: "MC", phoneExtension: "377"))
        countries.append(CountryPod(countryCode: "MN", phoneExtension: "976"))
        countries.append(CountryPod(countryCode: "ME", phoneExtension: "382"))
        countries.append(CountryPod(countryCode: "MS", phoneExtension: "1"))
        countries.append(CountryPod(countryCode: "MA", phoneExtension: "212"))
        countries.append(CountryPod(countryCode: "MZ", phoneExtension: "258"))
        countries.append(CountryPod(countryCode: "MM", phoneExtension: "95"))
        
        countries.append(CountryPod(countryCode: "NA", phoneExtension: "264"))
        countries.append(CountryPod(countryCode: "NR", phoneExtension: "674"))
        countries.append(CountryPod(countryCode: "NP", phoneExtension: "977"))
        countries.append(CountryPod(countryCode: "NL", phoneExtension: "31"))
        countries.append(CountryPod(countryCode: "AN", phoneExtension: "599"))
        countries.append(CountryPod(countryCode: "NC", phoneExtension: "687"))
        countries.append(CountryPod(countryCode: "NZ", phoneExtension: "64"))
        countries.append(CountryPod(countryCode: "NI", phoneExtension: "505"))
        countries.append(CountryPod(countryCode: "NE", phoneExtension: "227"))
        countries.append(CountryPod(countryCode: "NG", phoneExtension: "234"))
        countries.append(CountryPod(countryCode: "NU", phoneExtension: "683"))
        countries.append(CountryPod(countryCode: "KP", phoneExtension: "850"))
        countries.append(CountryPod(countryCode: "MP", phoneExtension: "1"))
        countries.append(CountryPod(countryCode: "NO", phoneExtension: "47"))
        
        countries.append(CountryPod(countryCode: "OM", phoneExtension: "968"))
        
        countries.append(CountryPod(countryCode: "PK", phoneExtension: "92"))
        countries.append(CountryPod(countryCode: "PW", phoneExtension: "680"))
        countries.append(CountryPod(countryCode: "PS", phoneExtension: "970"))
        countries.append(CountryPod(countryCode: "PA", phoneExtension: "507"))
        countries.append(CountryPod(countryCode: "PG", phoneExtension: "675"))
        countries.append(CountryPod(countryCode: "PY", phoneExtension: "595"))
        countries.append(CountryPod(countryCode: "PE", phoneExtension: "51"))
        countries.append(CountryPod(countryCode: "PH", phoneExtension: "63"))
        countries.append(CountryPod(countryCode: "PN", phoneExtension: "64"))
        countries.append(CountryPod(countryCode: "PL", phoneExtension: "48"))
        countries.append(CountryPod(countryCode: "PT", phoneExtension: "351"))
        countries.append(CountryPod(countryCode: "PR", phoneExtension: "1"))
        
        countries.append(CountryPod(countryCode: "QA", phoneExtension: "974"))
        
        countries.append(CountryPod(countryCode: "CG", phoneExtension: "242"))
        countries.append(CountryPod(countryCode: "RE", phoneExtension: "262"))
        countries.append(CountryPod(countryCode: "RO", phoneExtension: "40"))
        countries.append(CountryPod(countryCode: "RU", phoneExtension: "7"))
        countries.append(CountryPod(countryCode: "RW", phoneExtension: "250"))
        
        countries.append(CountryPod(countryCode: "BL", phoneExtension: "590"))
        countries.append(CountryPod(countryCode: "SH", phoneExtension: "290"))
        countries.append(CountryPod(countryCode: "KN", phoneExtension: "1"))
        countries.append(CountryPod(countryCode: "LC", phoneExtension: "1"))
        countries.append(CountryPod(countryCode: "MF", phoneExtension: "590"))
        countries.append(CountryPod(countryCode: "PM", phoneExtension: "508"))
        
        countries.append(CountryPod(countryCode: "VC", phoneExtension: "1"))
        countries.append(CountryPod(countryCode: "WS", phoneExtension: "685"))
        countries.append(CountryPod(countryCode: "SM", phoneExtension: "378"))
        countries.append(CountryPod(countryCode: "ST", phoneExtension: "239"))
        countries.append(CountryPod(countryCode: "SA", phoneExtension: "966"))
        countries.append(CountryPod(countryCode: "SN", phoneExtension: "221"))
        countries.append(CountryPod(countryCode: "RS", phoneExtension: "381"))
        countries.append(CountryPod(countryCode: "SC", phoneExtension: "248"))
        countries.append(CountryPod(countryCode: "SL", phoneExtension: "232"))
        countries.append(CountryPod(countryCode: "SG", phoneExtension: "65"))
        countries.append(CountryPod(countryCode: "SX", phoneExtension: "1"))
        countries.append(CountryPod(countryCode: "SK", phoneExtension: "421"))
        countries.append(CountryPod(countryCode: "SI", phoneExtension: "386"))
        countries.append(CountryPod(countryCode: "SB", phoneExtension: "677"))
        countries.append(CountryPod(countryCode: "SO", phoneExtension: "252"))
        countries.append(CountryPod(countryCode: "ZA", phoneExtension: "27"))
        countries.append(CountryPod(countryCode: "KR", phoneExtension: "82"))
        countries.append(CountryPod(countryCode: "SS", phoneExtension: "211"))
        countries.append(CountryPod(countryCode: "ES", phoneExtension: "34"))
        countries.append(CountryPod(countryCode: "LK", phoneExtension: "94"))
        countries.append(CountryPod(countryCode: "SD", phoneExtension: "249"))
        countries.append(CountryPod(countryCode: "SR", phoneExtension: "597"))
        countries.append(CountryPod(countryCode: "SJ", phoneExtension: "47"))
        countries.append(CountryPod(countryCode: "SZ", phoneExtension: "268"))
        countries.append(CountryPod(countryCode: "SE", phoneExtension: "46"))
        countries.append(CountryPod(countryCode: "CH", phoneExtension: "41"))
        countries.append(CountryPod(countryCode: "SY", phoneExtension: "963"))
        
        countries.append(CountryPod(countryCode: "TW", phoneExtension: "886"))
        countries.append(CountryPod(countryCode: "TJ", phoneExtension: "992"))
        countries.append(CountryPod(countryCode: "TZ", phoneExtension: "255"))
        countries.append(CountryPod(countryCode: "TH", phoneExtension: "66"))
        countries.append(CountryPod(countryCode: "TG", phoneExtension: "228"))
        countries.append(CountryPod(countryCode: "TK", phoneExtension: "690"))
        countries.append(CountryPod(countryCode: "TO", phoneExtension: "676"))
        countries.append(CountryPod(countryCode: "TT", phoneExtension: "1"))
        countries.append(CountryPod(countryCode: "TN", phoneExtension: "216"))
        countries.append(CountryPod(countryCode: "TR", phoneExtension: "90"))
        countries.append(CountryPod(countryCode: "TM", phoneExtension: "993"))
        countries.append(CountryPod(countryCode: "TC", phoneExtension: "1"))
        countries.append(CountryPod(countryCode: "TV", phoneExtension: "688"))
        
        countries.append(CountryPod(countryCode: "VI", phoneExtension: "1"))
        countries.append(CountryPod(countryCode: "UG", phoneExtension: "256"))
        countries.append(CountryPod(countryCode: "UA", phoneExtension: "380"))
        countries.append(CountryPod(countryCode: "AE", phoneExtension: "971"))
        countries.append(CountryPod(countryCode: "GB", phoneExtension: "44"))
        countries.append(CountryPod(countryCode: "US", phoneExtension: "1"))
        countries.append(CountryPod(countryCode: "UY", phoneExtension: "598"))
        countries.append(CountryPod(countryCode: "UZ", phoneExtension: "998"))
        
        countries.append(CountryPod(countryCode: "VU", phoneExtension: "678"))
        countries.append(CountryPod(countryCode: "VA", phoneExtension: "379"))
        countries.append(CountryPod(countryCode: "VE", phoneExtension: "58"))
        countries.append(CountryPod(countryCode: "VN", phoneExtension: "84"))
        
        countries.append(CountryPod(countryCode: "WF", phoneExtension: "681"))
        countries.append(CountryPod(countryCode: "EH", phoneExtension: "212"))
        
        countries.append(CountryPod(countryCode: "YE", phoneExtension: "967"))
        
        countries.append(CountryPod(countryCode: "ZM", phoneExtension: "260"))
        countries.append(CountryPod(countryCode: "ZW", phoneExtension: "263"))
        
        return countries
        }()
}
